### ISSUE TITLE
easy uninstall and reinstall

### ISSUE THREAD

**Issue by joestar9** [BLUEBL0B/Secret-Sing-Box#6]
hi there 😇

 Implement options to easily uninstall and reinstall:)

 using HTTP-UPGRADE instead of old web socket
 
 and if it possible to adding a document to manually running sing-box via nginx for education porpoises
 
 and thanks for your hard work (●'◡'●)

**Comment by BLUEBL0B** [comment]
Hello!
1) It's a good idea, I think I will implement it soon
2) Why do you prefer HTTPupgrade?
3) Here is the folder with all configs for setting up sing-box via nginx manually: https://github.com/BLUEBL0B/Secret-Sing-Box/tree/main/Config-Examples-WS
You just have to install the needed packages before replacing configs. There are just a few commands, you can look them up in the script.

**Comment by joestar9** [comment]
httpupgrade have better performance and it's more challenging for China and Iran firewalls to detect.
the only drawback is that it does not support early data in Sing-Box

**Comment by BLUEBL0B** [comment]
I think I will make an option in the script for this type of transport
